tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        upcBlue: '#003366',
                        upcGold: '#FFD700',
                        upcLight: '#F5F7FA',
                        upcDark: '#1A202C',
                    },
                    fontFamily: {
                        poppins: ['Poppins', 'sans-serif'],
                    },
                }
            }
        }

        
